# This is a basic workflow to help you get started with Actions

name: Cordova Bot

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-latest
        
    #os: [ubuntu-latest, windows-latest, macos-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
           
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: 🍎 This job is using ${{ runner.os }}.
      uses: actions/checkout@v2
    
    - name: 🏴 Setting up Java Environment for ${{ runner.os }}.
      uses: actions/setup-java@v2.1.0
      with: 
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '11'
        
    - name: 💞 settting up a Node.js 12 Environment.
      uses: actions/setup-node@v2
      with:
          node-version: '12'
      
    - name: 🍻 Installing the dependencies.          
      run: npm install
    
    - name: ⛳ Installing cordova.
      run: npm install -g cordova

    - name: Change Dir
      run: cd /Users/runner/work/Driver/Driver

    - name: List available Files for Cordova application.
      run: ls
    
    - name: Build command to build your application
      run: cordova info
    
    - name: Cordova Platforms List of Projects
      run: cordova platforms ls

    - name: Setup Android tools
      uses: maxim-lobanov/setup-android-tools@v1
      with:
        packages: ndk;21.4.7075529
        cache: true
        
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: latest-stable

    - name: Cordova Platforms requirements of Projects
      run: cordova requirements
  
    #- name: 🤖 No any problem found for android., Uploading APK to CI
    #  uses: actions/upload-artifact@v2.2.3
    #  with:
    #    name: lawsty-admin-${{ github.run_number }}
    #    path: build/app/outputs/flutter-apk/app-release.apk
        
    #- run: echo "❤️‍🔥 Download latest"
